require 'rubygems'
require 'rake'

require File.join(File.dirname(__FILE__), 'vendor', 'ruby', '1.8', 'gems', 'bundler-1.0.3', 'lib', 'bundler', 'setup')
Bundler.require

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = 'gemrage'
    gem.summary = %Q{Companion gem for gemrage.com}
    gem.description = %Q{Companion gem for gemrage.com}
    gem.email = 'darkhelmet@darkhelmetlive.com'
    gem.homepage = 'http://gemrage.com'
    gem.authors = ['Daniel Huckstep']
    gem.test_files = []
    #
    # We want NO DEPENDENCIES IN HERE!!!!!
    # We use bundler for stuff and then vendor it
    #

    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

=begin
require 'rspec/core/rake_task'
RSpec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

RSpec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :spec => :check_dependencies

task :default => :spec

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "gemrage #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

=end